import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Lock, Eye, Trash2, Database } from 'lucide-react';

const Privacy = () => {
  useEffect(() => { window.scrollTo(0, 0); }, []);

  return (
    <div className="min-h-screen bg-[#020617] text-slate-300 p-6 md:p-20 font-sans selection:bg-[#EE6A70]">
      <Link to="/" className="flex items-center gap-2 text-[#EE6A70] mb-12 font-bold group">
        <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform"/> Back to Home
      </Link>
      
      <h1 className="text-5xl font-black text-white mb-4 uppercase tracking-tighter">Privacy <span className="text-[#EE6A70]">Policy</span></h1>
      <p className="text-slate-500 mb-12 uppercase tracking-widest text-sm font-bold">Last Updated: March 2026</p>

      <div className="max-w-4xl space-y-12 text-lg leading-relaxed">
        <section>
          <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-4"><Database className="text-[#EE6A70]"/> 1. Data Collection</h2>
          <p>We believe in minimal data collection. When you use ClashDitto, we may collect and store:</p>
          <ul className="list-disc ml-8 mt-4 space-y-2 text-slate-400">
            <li><strong>User IDs & Guild IDs:</strong> To identify who is using the bot and in which server.</li>
            <li><strong>Clash of Clans Tags:</strong> Only if you provide them via commands like /player or /clan.</li>
            <li><strong>Command Usage Stats:</strong> We track how many times a command is used (anonymously) to improve the bot.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-4"><Eye className="text-[#EE6A70]"/> 2. How Data is Used</h2>
          <p>Your data is used strictly for the following:</p>
          <ul className="list-disc ml-8 mt-4 space-y-2 text-slate-400">
            <li>To fetch your game progress from the official Supercell API.</li>
            <li>To display your stats in the visual cards generated by the bot.</li>
            <li>To manage bot settings specific to your server.</li>
          </ul>
          <p className="mt-4 text-[#EE6A70] font-bold italic">Important: We NEVER sell, trade, or share your data with any third-party marketing agencies.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-4"><Lock className="text-[#EE6A70]"/> 3. Data Security</h2>
          <p>We use industry-standard encryption and secure MongoDB clusters to protect your information. Access to the database is restricted to the bot's core developers only.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white flex items-center gap-3 mb-4"><Trash2 className="text-[#EE6A70]"/> 4. Data Deletion</h2>
          <p>You have full control over your data. You can request to have your data deleted from our database at any time by:</p>
          <ul className="list-disc ml-8 mt-4 space-y-2 text-slate-400">
            <li>Removing the bot from your server (this stops data collection).</li>
            <li>Joining our Support Server and requesting a manual data wipe for your ID.</li>
          </ul>
        </section>
      </div>

      <div className="mt-20 pt-10 border-t border-white/5 text-slate-500 text-sm italic">
        This policy may be updated periodically. Your continued use of the bot signifies acceptance of these changes.
      </div>
    </div>
  );
};

export default Privacy;